import Head from "next/head";
import {
  GetHeaderSectionOne,
  GetHeaderSectionTwo,
} from "../redux/reducers/homeHeaderReducers";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import HomeComponentHeader from "../components/HomeComponentHeader";
import HomeSecondComponent from "../components/HomeSecondComponent";
import HomeServicesContainer from "../components/HomeServicesContainer";
import CaseStudies from "../components/CaseStudies";
import HomeReviewsContainer from "../components/HomeReviewsContainer";
export default function Home() {
  const dispatch = useDispatch();
  const {
    headerSecOne: { HeaderSectionOneData, HeaderSectionTwoData },
  } = useSelector((state) => state);

  useEffect(() => {
    // header section 1 dispatch
    dispatch(GetHeaderSectionOne())
      .unwrap()
      .then(() => {})
      .catch(() => {
        console.log("Error");
      });
    // header section 2 dispatch
    dispatch(GetHeaderSectionTwo())
      .unwrap()
      .then(() => {})
      .catch(() => {
        console.log("Error");
      });
  }, []);

  return (
    <div>
      <Head>
        <title>Alpha Web Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>

      <HomeComponentHeader data={HeaderSectionOneData[0]} />
      <HomeSecondComponent data={HeaderSectionTwoData[0]} />
      <HomeServicesContainer />
      <CaseStudies />
      <HomeReviewsContainer />

      <footer></footer>
    </div>
  );
}
